TexasTRInventory/Controllers/ApplicationUsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TexasTRInventory.Data;
using TexasTRInventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TexasTRInventory.Services;
using Microsoft.Extensions.Logging;
using TexasTRInventory.Constants;

namespace TexasTRInventory.Controllers
{
    [Authorize(Policy = Constants.PolicyNames.IsInternal)]
    public class ApplicationUsersController : Controller
    {
        private readonly InventoryContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        //12.7.17 adding more fields to do fancy authorization handling
        private readonly IAuthorizationService _authorizationService;

        public ApplicationUsersController(InventoryContext context, 
            UserManager<ApplicationUser> userManager,
            ILoggerFactory loggerFactory,
            IEmailSender emailSender,
            IAuthorizationService authorizationService)
        {
            _context = context;
            _userManager = userManager;
            _logger = loggerFactory.CreateLogger<ApplicationUsersController>();
            _emailSender = emailSender;
            _authorizationService = authorizationService;
        }

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.Include(p => p.Employer).ToListAsync());
        }
        
        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            //EXP 12.7.17. Make sure user has the right to edit this user
            bool isAuthorized = await _authorizationService.AuthorizeAsync(User, applicationUser, PolicyNames.OnlyAdminsEditAdmins);
            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            return EditViewWithEmployerList(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, /*[Bind("IsDisabled,EmployerID")]*/ ApplicationUser applicationUser)
        {            
            if (ModelState.IsValid)
            {
                try
                {

                    ApplicationUser dbUser = await _userManager.FindByIdAsync(id);

                    //EXP 12.7.17. Make sure user has the right to edit this user
                    bool isAuthorized = await _authorizationService.AuthorizeAsync(User, dbUser,PolicyNames.OnlyAdminsEditAdmins);
                    if (!isAuthorized)
                    {
                        return new ChallengeResult();
                    }

                    dbUser.EmployerID = applicationUser.EmployerID;
                    dbUser.IsDisabled = applicationUser.IsDisabled;
                    dbUser.IsAdmin = applicationUser.IsAdmin && Utils.IsAdmin(User); //Sneaky how I made this an and, instead of an if. less readable, but so clever
                    await _userManager.UpdateAsync(dbUser);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return EditViewWithEmployerList(applicationUser);
        }

        private IActionResult EditViewWithEmployerList(ApplicationUser applicationUser)
        {
            ViewData["EmployerID"] = Utils.CompanyList(_context, applicationUser.Employer, false); //TODO I think I know why the employer isn't loading
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser
                .AsNoTracking()
                .Include(u => u.Employer)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            bool isAuthorized = await _authorizationService.AuthorizeAsync(User, applicationUser, PolicyNames.OnlyAdminsEditAdmins);
            if (!isAuthorized)
            {
                return new ChallengeResult();
            }


            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);

            //EXP 12.7.17. Make sure user has the right to edit this user
            bool isAuthorized = await _authorizationService.AuthorizeAsync(User, applicationUser, PolicyNames.OnlyAdminsEditAdmins);
            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        //
        // GET: /Account/Register
        [HttpGet]
        public IActionResult Register()
        {

            ViewData["EmployerID"] = Utils.CompanyList(_context, excludeInternal: false);
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email,
                    Email = model.Email,
                    EmployerID = model.EmployerID,
                };

                IdentityResult result = await _userManager.CreateAsync(user);

                if (result.Succeeded)
                {
                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=532713
                    string msgBody = await EmailText(user);
                    await _emailSender.SendEmailAsync(model.Email, "Welcome to Texas TR!",msgBody);
                    _logger.LogInformation(3, "User created a new account");
                    return RedirectToAction(nameof(Index));

                }
                Utils.AddErrors(result, ModelState);
            }

            // If we got this far, something failed, redisplay form
            ViewData["EmployerID"] = Utils.CompanyList(_context, excludeInternal: false);
            return View(model);
        }

        private async Task<string> EmailText(ApplicationUser user)
        {
            string code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            string callbackUrl = Url.Action(nameof(AccountController.SetPassword), "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
            Company employer = await _context.Companies.FirstOrDefaultAsync(c => c.ID == user.EmployerID);

            string explanation = employer.IsInternal ?
                "An account has been created for you in our inventory management system." :
                $"You have been invited to record and track which products {employer.Name} sells with Texas TR.";

            string ret =
                $"Hello!<br><br>{explanation}<br>" +
                $"Please activate your account and set a password by clicking <a href='{callbackUrl}'>here</a>.<br><br>" +
                "Once your account is active, you can access the inventory management system at " +
                "<a href='https://texastrinventory.azurewebsites.net'>texastrinventory.azurewebsites.net</a>." +
                "<br><br> Sincerely,<br>Texas TR";
            return ret;
        }



        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

TexasTRInventory/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TexasTRInventory.Data;
using TexasTRInventory.Models;

namespace TexasTRInventory.Controllers
{
    
    public class CompaniesController : Controller
    {
        private readonly InventoryContext _context;
        
        public CompaniesController(InventoryContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            //This is the only line that is not shit.
            return View(await _context.Companies.ToListAsync());
        }
 
        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Company supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (id == GlobalCache.GetTexasTRCompanyID(_context))
            {
                return DontTouchTexasTR();
            }

            var supplier = await _context.Companies.SingleOrDefaultAsync(m => m.ID == id);
            if (supplier == null) //TODO -- also exclude internal supplier. But first let me deal with the post method
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Company supplier)
        {
            if (id != supplier.ID)
            {
                return NotFound();
            }

            //EXP 9.22.17. Don't let people edit TexasTR
            if (id==GlobalCache.GetTexasTRCompanyID(_context))
            {
                return DontTouchTexasTR();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException ex)
                {
                    if (Utils.IsUniqueKeyViolation(ex.InnerException))
                    {
                        ModelState.AddModelError(string.Empty, "The database could not accept your edits. Each company must have a unique name.");
                        return View(supplier);
                    }

                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

/*            if (id == GlobalCache.GetTexasTRCompanyID(_context))
            {
                return DontTouchTexasTR();
            }
            */
            var supplier = await _context.Companies
                .SingleOrDefaultAsync(m => m.ID == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == GlobalCache.GetTexasTRCompanyID(_context))
            {
                return DontTouchTexasTR();
            }
            var supplier = await _context.Companies.SingleOrDefaultAsync(m => m.ID == id);
            _context.Companies.Remove(supplier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool SupplierExists(int id)
        {
            return _context.Companies.Any(e => e.ID == id);
        }

        private IActionResult DontTouchTexasTR()
        {
            ViewData[Constants.KeyNames.ErrorDetails] = "You cannot edit or delete the Texas TR record.";
            return View("Error");
        }
    }
}

TexasTRInventory/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Texas TR Inventory Management System</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse"> @*EXP 9.25.17 deleting navbar fixed top after conferring with YMP*@
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Texas TR Inventory Management System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*EXP now the buttons I'm adding*@
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    @*EXP 9.18.17 Buttons visiable only to internals*@
                    @if (Utils.IsInternalUser(User))
                    {
                        <li><a asp-area="" asp-controller="Companies" asp-action="Index">Companies</a></li>
                        <li><a asp-area="" asp-controller="ApplicationUsers" asp-action="Index">Users</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <small>
                    &copy; 2017 Texas TR <a href="http://www.texastr.com">TexasTR.com</a>
                </small>
            </p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>