TexasTRInventory/Controllers/CSVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TexasTRInventory.Data;
using TexasTRInventory.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;//EXP 9.13.17. From here to the end, all bullshit
using Microsoft.AspNetCore.Identity;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Reflection;
using System.Text;
using Microsoft.AspNetCore.Authorization;

namespace TexasTRInventory.Controllers
{
    [Authorize(Policy = Constants.PolicyNames.IsInternal)]
    public class CSVsController : Controller
	{
		//We need some blob stuff, and that should be put in using DI. But we cannot. I forgot why. But I remember that it was a formidible technical challenge
		private readonly InventoryContext _context;

		public CSVsController(InventoryContext context)
		{
			_context = context;
		}




		// GET: CSVs
		public async Task<IActionResult> Index()
		{

			List<CSVViewModel> CSVs = new List<CSVViewModel>();
			CloudBlobContainer blobs = await GlobalCache.GetCSVContainer();
			foreach (IListBlobItem blob in blobs.ListBlobs())
			{
				if (blob.GetType() == typeof(CloudBlockBlob))
				{
					CSVs.Add(new CSVViewModel((CloudBlockBlob)blob));
				}
			}

			CSVs.Sort((x,y) => DateTimeOffset.Compare((DateTimeOffset)(x.Modified), (DateTimeOffset)(y.Modified)));

            return View(CSVs);
		}
	
		// GET: CSVs/Create
		public async Task<IActionResult> Create()
		{
			StringBuilder file = new StringBuilder();
            //Get the column headers
            
			foreach(PropertyInfo pi in typeof(ProductDBModel).GetProperties())
			{
                //When it starts with capital ID, it makes Excel throw errors. I don't want to make my code ugly because MS Excel is stupid. But I will.
                if (pi.Name=="ID")
                {
                    file.Append("Product ID,");
                    continue;
                }

                file.Append(pi.Name);
				file.Append(',');
			}
            file.Remove(file.Length - 1, 1);

            file.Append('\n');

			foreach (ProductDBModel product in _context.Products.AsNoTracking())
			{
				AppendProduct(product, ref file);
				file.Append('\n');
			}

			file.Remove(file.Length - 1, 1);

			//Got the file in a long string. let's get it into a file
			CloudBlockBlob blob = await GlobalCache.GetCSVBlob(CSVFileName());
            blob.Properties.ContentType = "text/csv";
            blob.UploadText(file.ToString());
            
			return RedirectToAction("Index");
		}

		private void AppendProduct(ProductDBModel product, ref StringBuilder sb)
		{
			foreach (PropertyInfo pi in product.GetType().GetProperties())
			{
				var val = pi.GetValue(product) ?? string.Empty;
                AppendCell(sb, val.ToString());
			}

			sb.Remove(sb.Length - 1, 1);
		}

        //Copied from https://stackoverflow.com/questions/6377454/escaping-tricky-string-to-csv-format
        private void AppendCell(StringBuilder sb, string value)
        {
            bool mustQuote = (value.Contains(',')
                            || value.Contains('\"')
                            || value.Contains('\r')
                            || value.Contains('\n'));

            if (mustQuote)
            {
                sb.Append('\"');
                foreach (char nextChar in value)
                {
                    sb.Append(nextChar);
                    if (nextChar == '"') sb.Append('\"');
                }
                sb.Append('\"');
            }
            else
            {
                sb.Append(value);
            }
        }

        private string CSVFileName()
		{
			return DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss-fff")+".csv";
		}

		//POST: CSVs
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Index(List<CSVViewModel> CSVList)
		{
			for(int i=CSVList.Count-1; i>=0; i--)//I'm so clever. If I iterate backwards, I can modify the list while I'm iterating.
            {
                CSVViewModel file = CSVList[i];
                if (file.ShouldBeDeleted)
                {
                    CloudBlockBlob blob = await GlobalCache.GetCSVBlob(file.Name);
                    await blob.DeleteIfExistsAsync();
                    CSVList.RemoveAt(i);
                }
            }
            return View(CSVList);
		}
	}
}

TexasTRInventory/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal;
using Microsoft.EntityFrameworkCore;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;
using TexasTRInventory.Constants;
using TexasTRInventory.Data;
using TexasTRInventory.Models;

namespace TexasTRInventory.Controllers
{

    [Authorize]
    public class ProductsController : Controller
    {
        private readonly InventoryContext _context;
        private readonly IAuthorizationService _authorizationService;

        public ProductsController(InventoryContext context, IAuthorizationService authorizationService)
        {
            _context = context;
            _authorizationService = authorizationService;
        }

        // POST: Products
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = PolicyNames.IsAdmin)]
        public async Task<IActionResult> Index(IList<ProductViewModel> pvms, string sortOrder, int? pageNum, string pageSize)
        {
            Dictionary <int,bool> approvals = pvms.ToDictionary(p => p.ID, p=> p.IsAdminApproved);
            var pdms = await _context.Products.Where(p => approvals.ContainsKey(p.ID)).ToListAsync();
            pdms.ForEach(p => p.IsAdminApproved = approvals[p.ID]);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index","Products",
                new Dictionary<string, object>()
                {
                    {nameof(sortOrder), sortOrder },
                    {nameof(pageNum), pageNum },
                    {nameof(pageSize), pageSize }
                }
            );
        }

        // GET: Products
        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder, int? pageNum, string pageSize)
        {
			IQueryable<ProductDBModel> products;
            if (Utils.IsInternalUser(User))
            {
                products = _context.Products.Include(p => p.Supplier);
            }
            else
            {
                int? supplierID = Utils.SupplierID(User);
                products = _context.Products.Where(p => p.SupplierID == supplierID);
            }

            //EXP 9.28.17. Interpreting the sortOrderParam
            //ViewData["CurrentSort"] = sortOrder; //EXP 2.26.18. I think this should be deleted, because i'm not implementing it the way MS did
            ViewData["SKUSortParm"] = String.IsNullOrEmpty(sortOrder) ? "SKU_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["ApprovalSortParm"] = sortOrder == "approval" ? "approval_desc" : "approval";

            switch (sortOrder)
            {
                case "SKU_desc":
                    products = products.OrderByDescending(p => p.SKU);
                    break;
                case "name":
                    products = products.OrderBy(p => p.Name);
                    break;
                case "name_desc":
                    products = products.OrderByDescending(p => p.Name);
                    break;
                case "approval":
                    products = products.OrderBy(p => p.IsAdminApproved);
                    break;
                case "approval_desc":
                    products = products.OrderByDescending(p => p.IsAdminApproved);
                    break;
                default:
                    products = products.OrderBy(s => s.SKU);
                    break;
            }

            int pageSizeInt;
            if (!int.TryParse(pageSize, out pageSizeInt))
            {
                pageSizeInt = int.MaxValue;
            }

            IQueryable<Task<ProductViewModel>> pvms = products.AsNoTracking().Select(p => ProductViewModel.FromDBProduct(p));
            var pl = await PaginatedList<ProductViewModel>.CreateAsync(pvms, pageNum ?? 1, pageSizeInt);
            return View(pl);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Supplier)
                .Include(p => p.ImageFilePaths)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            if (!User.IsOwnProduct(product))
            {
                return HiddenProductError();
            }

            ProductViewModel pvm = await ProductViewModel.FromDBProduct(product);
            return View(pvm);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return ViewWithSupplierList();
        }
        
        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (ProductViewModel pvm)
        {
			if(!ModelState.IsValid)return ViewWithSupplierList(); ;

            ProductDBModel product = null;
            try
            {
                product = await pvm.ToProductDB();
            }
            catch (FileUploadFailedException e)
            {
                Expression<Func<ProductViewModel, IFormFileCollection>> expression = p => p.ImageFiles;
                string key = ExpressionHelper.GetExpressionText(expression);
                ModelState.AddModelError(key, e.Message);
            }

            if (ModelState.IsValid)
            {
                product.SupplierID = Utils.IsInternalUser(User) ? product.SupplierID : Utils.SupplierID(User);
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return ViewWithSupplierList();
        }



        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Supplier)
                .Include(p => p.ImageFilePaths)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            if (!User.IsOwnProduct(product))
            {
                return HiddenProductError();
            }

            if (await FailsLockedProductPolicy(product))
            {
                return new ChallengeResult();
            }

            ViewData["SupplierID"] = Utils.CompanyList(_context, product.Supplier);
            var pvm = await ProductViewModel.FromDBProduct(product);
            //return View("Edit old version, before sharing",pvm);
            return View(pvm);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel product)
        {
            ProductDBModel existingProduct = await _context.Products.Include(p => p.ImageFilePaths).SingleOrDefaultAsync(m => m.ID == product.ID);

            if (id != product.ID || existingProduct == null)
            {
                return NotFound();
            }

            if (!User.IsOwnProduct(existingProduct))
            {
                return HiddenProductError();
            }

            if (await FailsLockedProductPolicy(product))
            {
                return new ChallengeResult();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ProductDBModel pdb = await product.ToProductDB(existingProduct);
                    DeleteOldImages(product, existingProduct.ImageFilePaths);

                    //now merge pdb with existing product
                    foreach(PropertyInfo pi in typeof(ProductDBModel).GetProperties())
                    {
                        var attr = pi.GetCustomAttribute<RestrictedFieldAttribute>(true);
                        if (attr == null || attr.CanUserEdit(User))
                        {
                            var value = pi.GetValue(pdb);
                            pi.SetValue(existingProduct, value);
                        }
                    }
                    await _context.SaveChangesAsync();
                    /* handled more generically above
                    if (!Utils.IsInternalUser(User))
                    {
                        pdb.SupplierID = existingProduct.SupplierID;
                    }*/
                }
                catch (FileUploadFailedException e)
                {
                    Expression<Func<ProductViewModel, IFormFileCollection>> expression = p => p.ImageFiles;
                    string key = ExpressionHelper.GetExpressionText(expression);
                    ModelState.AddModelError(key, e.Message);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

TexasTRInventory/Views/Products/Create old version, before sharing.cshtml
@model TexasTRInventory.Models.ProductViewModel

@{
    ViewData["Title"] = "Create";
}

@*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
<script src="~/js/3rdParty/Load-Image/js/load-image.all.min.js"></script> @*TODO maybe load directly from the internet and fallback on my copy?*@

@*not sure what each of these do. But they're recommended by https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation#client-side-validation*@
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.js"></script> @*temporarly replacing .min.js with .js*@
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.js"></script>
<script src="~/ts/product.js"></script>

<h2>Create</h2>
<form asp-action="Create" enctype="multipart/form-data" method="post">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Brand" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SKU" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SKU" class="form-control" />
                <span asp-validation-for="SKU" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Info" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @*<input asp-for="Info" class="form-control" />*@
                @Html.TextArea("Info",null/*TODO make sure that existing text is included*/, 5,200
               ,null)
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PackageContents" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PackageContents" class="form-control" />
                <span asp-validation-for="PackageContents" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OurCost" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OurCost" class="form-control" />
                <span asp-validation-for="OurCost" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MAP" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MAP" class="form-control" />
                <span asp-validation-for="MAP" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Dimensions" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Dimensions" class="form-control" />
                <span asp-validation-for="Dimensions" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Weight" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="UPC" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UPC" class="form-control" />
                <span asp-validation-for="UPC" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Website" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
        </div>
        <div style="display:none">
            <div class="col-md-10" id="fileUploaderTemplate">
                <span>
                    <input multiple="" asp-for="ImageFiles" id="fileInputer" onchange="previewFile(this);" style="float:left" class="sufficientimages"/>
                    <button type="button" onclick="resetField(this);" style="visibility:hidden; float:left">🗙</button>
                    <script>
                        var inputField = document.getElementById("fileInputer");
                        inputField.accept = "image/*";
                        inputField.removeAttribute("multiple");
                    </script>
                </span>
                <br />
                <div class="imagePreview" style="clear: both;"></div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageFiles" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <div id="dynamicallyGrowingDiv">
                </div>
                <script>initializeFields("dynamicallyGrowingDiv","fileUploaderTemplate",@GlobalCache.MinImgFilesCnt()); </script>
                <div class="col-md-10">
                    <input type="button" onclick="addFileField('dynamicallyGrowingDiv','fileUploaderTemplate')" value="add more files" />
                    <div><span asp-validation-for="ImageFiles" class="text-danger"></span></div>
                </div>
            </div>
        </div>

        @if (Utils.IsInternalUser(User))
        {
            <div class="form-group">
                <label asp-for="SupplierID" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="SupplierID" class="form-control" asp-items=ViewBag.SupplierID></select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PartNumber" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="PartNumber" class="form-control" />
                    <span asp-validation-for="PartNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Inventory" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Inventory" class="form-control" />
                    <span asp-validation-for="Inventory" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="AmazonASIN" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="AmazonASIN" class="form-control" />
                    <span asp-validation-for="AmazonASIN" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Dealer" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Dealer" class="form-control" />
                    <span asp-validation-for="Dealer" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Category" class="form-control" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
            </div>

        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TexasTRInventory/Views/Products/Create.cshtml
@model TexasTRInventory.Models.ProductViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<form asp-action="Create" enctype="multipart/form-data" method="post">
        <div class="form-group">
            @Html.Partial("SharedWrite");
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TexasTRInventory/Views/Products/Delete.cshtml
@model TexasTRInventory.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this product?</h3>

@Html.Partial("SharedRead");
    
<form asp-action="Delete">
    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </div>
</form>

TexasTRInventory/Views/Products/Details.cshtml
@model TexasTRInventory.Models.Product

@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>
<!--<script src="~/js/product.js"></script> This really should be in SharedRead.cshtml-->
@Html.Partial("SharedRead")
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TexasTRInventory/Views/Products/Edit.cshtml
@model TexasTRInventory.Models.ProductViewModel

@using TexasTRInventory.Models

@{
        ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit" enctype="multipart/form-data" method="post">
    <input hidden="hidden" asp-for="ID" />    
    @Html.Partial("SharedWrite")
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TexasTRInventory/Views/Products/Index as it existed before stuffing the table in its own file.cshtml
@model TexasTRInventory.PaginatedList<TexasTRInventory.Models.ProductViewModel>
@using TexasTRInventory.ExternalUtils
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "Products";
    IQueryCollection q = Context.Request.Query;
    //some query string parameter names:
    string sortOrder = "sortOrder";
    string pageNum = "pageNum";
    string pageSize = "pageSize";
}

<h2>@ViewData["Title"]</h2>

    <p>
        <a asp-action="Create">Create a New Product</a>
        @if (Utils.IsInternalUser(User))
        {
            <br />
            <a asp-controller="CSVs" > See All Products in CSV form</a >
        }
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-all-route-data=@General.AugmentedQueryString(q, sortOrder,ViewData["ApprovalSortParm"].ToString()).PrunedQueryString(pageNum)>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().IsAdminApproved)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Brand)
            </th>
            <th>
                <a asp-action="Index" asp-all-route-data=@General.AugmentedQueryString(q, sortOrder,ViewData["SKUSortParm"].ToString()).PrunedQueryString(pageNum)>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().SKU)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-all-route-data=@General.AugmentedQueryString(q,sortOrder,ViewData["NameSortParm"].ToString()).PrunedQueryString(pageNum)>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                </a>
            </th>
            <th style=" max-width: 200000px;">

                @Html.DisplayNameFor(model => model.FirstOrDefault().Info)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().OurCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().MAP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Dimensions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().UPC)
            </th>
            @if (Utils.IsInternalUser(User))
            {
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Supplier)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().PartNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Dealer)
                </th>
            }
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
       <td>
                @if (ApplicationUserUtils.IsAdmin(User))
                {
                    @Html.DisplayFor(modelItem => item.IsAdminApproved);
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.IsAdminApprovedStr);
                }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.SKU)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>

        <td style=" max-width: 200000px;">
            @Html.DisplayFor(modelItem => item.Info)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.OurCost)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.MAP)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Dimensions)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.UPC)
        </td>
            @*EXP 9.18.17. hiding this for external users*@
            @if(Utils.IsInternalUser(User))
            {
                <td>
                @Html.DisplayFor(modelItem => item.Supplier.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dealer)
                </td>

}
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> <br/>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a><br />
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a><br />
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-all-route-data=@General.AugmentedQueryString(q,pageNum,(Model.PageIndex-1).ToString())
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-all-route-data=@General.AugmentedQueryString(q,pageNum,(Model.PageIndex+1).ToString())
   class="btn btn-default @nextDisabled">
    Next
</a>

Products per page:

@{
    string[] pageSizes = { "10", "20", "50", "100", "all" };
    foreach (string size in pageSizes)
    {
        <a asp-action="Index" asp-all-route-data=@General.AugmentedQueryString(q,pageSize,size)>@size</a>
    }
}

TexasTRInventory/Views/Products/Index.cshtml
@using TexasTRInventory.ExternalUtils

<h2>@ViewData["Title"]</h2>

    <p>
        <a asp-action="Create">Create a New Product</a>
        @if (ApplicationUserUtils.IsInternalUser(User))
        {
            <br />
            <a asp-controller="CSVs" > See All Products in CSV form</a >
        }
    </p>
@if (ApplicationUserUtils.IsAdmin(User))
{
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        @Html.Partial("Table")
        <br/><br/>
        <div class="form-group">
            <input type="submit" value="Update approval statuses" class="btn btn-default" disabled="disabled" id="btnSubmit"/>
        </div>
    }
}
else
{
    @Html.Partial("Table");
}